#!/usr/bin/env bash
#
# gen_sample_report.sh — regenerate tests/provenance_fixture/sample_report.md.
#
# Builds two diverging fixture sessions (variant A = full pipeline; variant B =
# skips the techstack agent, phones home on validation, burns more tokens), then
# runs `provenance_ref.py compare` and writes the result to sample_report.md.
# The committed sample_report.md is the artifact reviewers read; rerun this to
# refresh it (it is generated — do not hand-edit).
#
# Usage: tests/provenance_fixture/gen_sample_report.sh

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=lib_build.sh
source "$SCRIPT_DIR/lib_build.sh"
prov_require_deps

BUILD_A="$(mktemp -d)"; GNUPG_A=""
BUILD_B="$(mktemp -d)"; GNUPG_B=""
cleanup() { rm -rf "$BUILD_A" "$BUILD_B" "$GNUPG_A" "$GNUPG_B" "${GNUPGHOME:-}"; }
trap cleanup EXIT

echo "── build A (full pipeline) ───────────────────────────────────────────"
prov_build_known_good "$BUILD_A" a
SA="$BUILD_A/$PROV_SESSION_DIR"; GNUPG_A="${GNUPGHOME:-}"

echo "── build B (diverges: skips techstack, phones home, more tokens) ──────"
prov_build_known_good "$BUILD_B" b
SB="$BUILD_B/$PROV_SESSION_DIR"; GNUPG_B="${GNUPGHOME:-}"

OUT="$SCRIPT_DIR/sample_report.md"
{
  echo "<!-- Generated by tests/provenance_fixture/gen_sample_report.sh — do not hand-edit. -->"
  echo "<!-- Session ids and hashes vary per run; the SHAPE of the comparison is the point. -->"
  echo
  python3 "$PROV_REF" compare "$SA" "$SB"
} > "$OUT"

echo "✓ wrote $OUT"
